name: Update JSON and Export Excel

on:
  workflow_dispatch:
    inputs:
      submission:
        description: "Form Submission Data"
        required: true

permissions:
  contents: write

jobs:
  update_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Existing JSON Data
        env:
          GITHUB_TOKEN: ${{ secrets.SCORECARD }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/mukucoder87/fpsc2/contents/data/submissions.json \
               | jq -r '.content' | base64 --decode > data/submissions.json || echo "[]" > data/submissions.json

      - name: Append New Data to JSON
        run: |
          echo '${{ github.event.inputs.submission }}' > form_submission.json
          jq --slurpfile newData form_submission.json '. + $newData' data/submissions.json > updated_submissions.json
          cat updated_submissions.json

      - name: Commit and Push Updated JSON
        env:
          GITHUB_TOKEN: ${{ secrets.SCORECARD }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mv updated_submissions.json data/submissions.json
          git add data/submissions.json
          git commit -m "New form submission via GitHub Actions" || echo "No changes to commit"
          git push https://x-access-token:$GITHUB_TOKEN@github.com/mukucoder87/fpsc2.git HEAD:main

      - name: Install Python Dependencies
        run: |
          pip install pandas openpyxl
        shell: bash

      - name: Convert JSON to Excel
        run: |
          python - <<'EOF'
          import pandas as pd
          import json
          with open('data/submissions.json', 'r') as f:
              data = json.load(f)
          df = pd.json_normalize(data, sep='_')
          df.to_excel('data/submissions.xlsx', index=False)
          EOF
        shell: bash

      - name: Commit and Push Excel File
        env:
          GITHUB_TOKEN: ${{ secrets.SCORECARD }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/submissions.xlsx
          git commit -m "Update Excel file with new submissions" || echo "No changes to commit"
          git push https://x-access-token:$GITHUB_TOKEN@github.com/mukucoder87/fpsc2.git HEAD:main
